---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lakeviex/public_html
    - /bin/mkdir -p $DEPLOYPATH/build $DEPLOYPATH/images
    - /bin/rm -f $DEPLOYPATH/setup.php
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage
    - /bin/chmod -R 775 $DEPLOYPATH/bootstrap/cache
