<template>
    <AdminLayout active-menu="products" page-title="Products">
        <div class="space-y-5">
            <div class="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><p class="text-xs uppercase tracking-[.2em] text-brand-400 font-bold">Catalog control</p><h2 class="font-serif text-3xl font-bold text-brand-900 mt-2">Branch-wise products</h2><p class="text-sm text-brand-500 mt-2">Set where each product is available and customize outlet pricing.</p></div><button @click="openModal()" class="bg-brand-700 text-white rounded-full px-5 py-3 text-sm font-bold hover:bg-brand-600 transition">+ Add product</button></div>
            <div class="bg-white rounded-2xl border border-brand-100 shadow-soft p-4 flex flex-col sm:flex-row gap-3"><div class="relative flex-1"><svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-brand-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="m21 21-4.35-4.35m2.35-5.15a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/></svg><input v-model="search" @input="debouncedSearch" type="search" placeholder="Search products..." class="w-full rounded-xl border border-brand-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100" /></div><select v-model="categoryFilter" @change="doFilter" class="rounded-xl border border-brand-200 bg-white px-3 py-2.5 text-sm text-brand-700 outline-none focus:border-brand-500"><option value="">All categories</option><option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option></select></div>
            <div class="bg-white rounded-2xl border border-brand-100 shadow-soft overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[760px]"><thead class="bg-brand-50 border-b border-brand-100"><tr><th class="table-head">Product</th><th class="table-head">Category</th><th class="table-head">Base price</th><th class="table-head">Outlets</th><th class="table-head">Status</th><th class="table-head">Actions</th></tr></thead><tbody class="divide-y divide-brand-100"><tr v-for="product in products.data" :key="product.id" class="hover:bg-cream-50 transition"><td class="table-cell"><div class="flex items-center gap-3"><div class="w-11 h-11 rounded-xl bg-brand-50 overflow-hidden flex items-center justify-center"><img v-if="product.image" :src="assetUrl(product.image)" class="w-full h-full object-cover"/><span v-else class="text-xl">🍰</span></div><div><div class="font-semibold text-brand-900">{{ product.name }}</div><div class="text-xs text-brand-400">#{{ product.id }}</div></div></div></td><td class="table-cell text-brand-500">{{ product.category?.name }}</td><td class="table-cell font-semibold text-brand-700">৳{{ money(product.effective_price) }}</td><td class="table-cell"><span class="inline-flex items-center gap-1.5 rounded-full bg-sage-50 px-2.5 py-1 text-xs font-bold text-sage-700"><span class="w-1.5 h-1.5 rounded-full bg-sage-400"></span>{{ product.branches_count || product.branches?.length || 0 }} outlets</span></td><td class="table-cell"><span :class="product.is_available ? 'status-success' : 'status-danger'">{{ product.is_available ? 'Available' : 'Hidden' }}</span></td><td class="table-cell"><button @click="openModal(product)" class="text-brand-600 hover:text-brand-500 font-semibold text-sm mr-4">Edit</button><button @click="deleteProduct(product)" class="text-red-500 hover:text-red-700 font-semibold text-sm">Delete</button></td></tr><tr v-if="!products.data?.length"><td colspan="6" class="p-12 text-center text-sm text-brand-500">No products found.</td></tr></tbody></table></div><div v-if="products.links?.length > 1" class="p-4 flex justify-center gap-2 border-t border-brand-100"><Link v-for="(link, i) in products.links" :key="i" :href="link.url || '#'" :class="link.active ? 'bg-brand-700 text-white border-brand-700' : 'bg-white text-brand-700 border-brand-200'" class="rounded-full border px-3 py-1.5 text-xs font-bold" v-html="link.label" :preserve-scroll="true" /></div></div>
        </div>

        <div v-if="showModal" class="fixed inset-0 z-[100] bg-brand-950/60 backdrop-blur-sm p-4 flex items-center justify-center" @click.self="showModal = false"><div class="w-full max-w-2xl max-h-[92vh] overflow-y-auto rounded-3xl bg-cream-50 shadow-2xl p-6 sm:p-8"><div class="flex items-start justify-between gap-4 mb-6"><div><p class="text-xs uppercase tracking-[.2em] text-brand-400 font-bold">Catalog item</p><h3 class="font-serif text-2xl font-bold text-brand-900 mt-2">{{ editing ? 'Edit product' : 'Add product' }}</h3></div><button @click="showModal = false" class="w-9 h-9 rounded-full bg-brand-100 text-brand-600">×</button></div><form @submit.prevent="saveProduct" class="space-y-5"><div class="grid sm:grid-cols-2 gap-4"><label class="field-label">Product name<input v-model="form.name" required class="field-input" /></label><label class="field-label">Category<select v-model="form.category_id" required class="field-input"><option value="">Select category</option><option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option></select></label></div><div class="grid sm:grid-cols-2 gap-4"><label class="field-label">Base price (৳)<input v-model="form.price" type="number" step="0.01" min="0" required class="field-input" /></label><label class="field-label">Base discount price (৳)<input v-model="form.discount_price" type="number" step="0.01" min="0" class="field-input" /></label></div><label class="field-label">Description<textarea v-model="form.description" rows="3" class="field-input"></textarea></label><label class="field-label">Product image<input @change="e => form.image = e.target.files[0]" type="file" accept="image/*" class="field-input file:mr-3 file:rounded-full file:border-0 file:bg-brand-100 file:px-3 file:py-1 file:text-xs file:font-bold file:text-brand-700" /></label>
                    <div class="grid sm:grid-cols-2 gap-4">
                        <label class="field-label">Delivery options<select v-model="form.delivery_mode" class="field-input"><option value="inherit">Use category setting</option><option value="both">Pickup & Home Delivery</option><option value="pickup">Pickup preferred</option><option value="home_delivery">Home Delivery only</option></select><span class="block mt-1 text-xs font-normal text-brand-400">Home delivery is available for every product. This setting controls pickup availability.</span></label>
                        <div class="rounded-xl border border-brand-200 bg-brand-50/60 px-4 py-3 text-xs text-brand-600"><strong class="text-brand-800">Smart delivery</strong><br/>Home delivery is always available; pickup can be limited from this setting.</div>
                    </div>
                    <div class="rounded-2xl border border-brand-200 bg-white p-4"><div class="flex items-start justify-between gap-4"><div><h4 class="font-bold text-brand-900">Product gallery</h4><p class="text-xs text-brand-500 mt-1">Add multiple supporting images for the product page. The cover image is selected above.</p></div><span class="text-xs font-bold text-brand-500">{{ form.gallery.length + form.existing_gallery.length }} gallery images</span></div><div class="mt-4"><label class="field-label">Gallery images<input @change="handleGalleryFiles" type="file" accept="image/*" multiple class="field-input file:mr-3 file:rounded-full file:border-0 file:bg-brand-100 file:px-3 file:py-1 file:text-xs file:font-bold file:text-brand-700" /><span class="block mt-1 text-xs font-normal text-brand-400">Multiple JPG, PNG or WEBP · max 4MB each</span></label></div><div v-if="galleryError" class="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs text-red-700">{{ galleryError }}</div><div v-if="form.existing_gallery.length || form.gallery.length" class="grid grid-cols-4 sm:grid-cols-6 gap-2 mt-4"><div v-for="path in form.existing_gallery" :key="path" class="relative aspect-square rounded-xl overflow-hidden border border-brand-200"><img :src="assetUrl(path)" class="w-full h-full object-cover"/><button type="button" @click="removeExistingImage(path)" class="absolute top-1 right-1 w-6 h-6 rounded-full bg-white/90 text-red-600 text-sm shadow">×</button></div><div v-for="(file, index) in form.gallery" :key="file.name + index" class="relative aspect-square rounded-xl overflow-hidden border border-gold-200 bg-gold-50 flex items-center justify-center"><span class="px-1 text-center text-[10px] font-semibold text-brand-700 break-words">{{ file.name }}</span><button type="button" @click="form.gallery.splice(index, 1)" class="absolute top-1 right-1 w-6 h-6 rounded-full bg-white/90 text-red-600 text-sm shadow">×</button></div></div></div>
                    <div class="rounded-2xl border border-brand-200 bg-white p-4"><div class="flex items-start justify-between gap-4"><div><h4 class="font-bold text-brand-900">Outlet availability</h4><p class="text-xs text-brand-500 mt-1">Enable this product at selected outlets. Leave prices blank to use the base price.</p></div><span class="text-xs font-bold text-brand-500">{{ enabledCount }}/{{ branches.length }} selected</span></div><div class="mt-4 space-y-3"> <div v-for="assignment in form.branch_assignments" :key="assignment.branch_id" class="rounded-xl border p-3" :class="assignment.enabled ? 'border-brand-300 bg-brand-50/60' : 'border-brand-100 bg-cream-50'"><div class="flex items-center gap-3"><input v-model="assignment.enabled" type="checkbox" class="h-4 w-4 rounded border-brand-300 text-brand-600 focus:ring-brand-200"/><div class="min-w-0 flex-1"><div class="text-sm font-semibold text-brand-900 truncate">{{ branchName(assignment.branch_id) }}</div><div class="text-[11px] text-brand-400">{{ assignment.is_available ? 'Available for ordering' : 'Hidden from customers' }}</div></div><label v-if="assignment.enabled" class="inline-flex items-center gap-1.5 text-[11px] text-brand-600"><input v-model="assignment.is_available" type="checkbox" class="h-3.5 w-3.5 rounded border-brand-300 text-brand-600"/> Live</label></div><div v-if="assignment.enabled" class="grid grid-cols-3 gap-2 mt-3"><label class="text-[10px] font-bold uppercase tracking-wide text-brand-400">Price<input v-model="assignment.price" type="number" min="0" step="0.01" placeholder="Base" class="branch-input"/></label><label class="text-[10px] font-bold uppercase tracking-wide text-brand-400">Discount<input v-model="assignment.discount_price" type="number" min="0" step="0.01" placeholder="Optional" class="branch-input"/></label><label class="text-[10px] font-bold uppercase tracking-wide text-brand-400">Stock<input v-model="assignment.stock" type="number" min="0" placeholder="Unlimited" class="branch-input"/></label></div></div></div></div>
                    <div class="flex flex-wrap gap-4"><label class="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><input v-model="form.is_available" type="checkbox" class="rounded border-brand-300 text-brand-600"/> Product globally active</label><label class="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><input v-model="form.is_featured" type="checkbox" class="rounded border-brand-300 text-brand-600"/> Feature on home</label></div><div class="flex gap-3 pt-2"><button type="submit" :disabled="saving" class="flex-1 rounded-full bg-brand-700 py-3 text-sm font-bold text-white hover:bg-brand-600 disabled:opacity-60">{{ saving ? 'Saving...' : editing ? 'Save changes' : 'Create product' }}</button><button type="button" @click="showModal = false" class="rounded-full border border-brand-200 px-6 py-3 text-sm font-bold text-brand-700 hover:bg-white">Cancel</button></div>
                </form></div></div>
    </AdminLayout>
</template>

<script setup>
import AdminLayout from '@/Layouts/AdminLayout.vue';
import { Link, router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

const props = defineProps({ products: Object, categories: Array, branches: Array, filters: Object });
const showModal = ref(false); const editing = ref(null); const saving = ref(false); const search = ref(props.filters?.search || ''); const categoryFilter = ref(props.filters?.category_id || ''); let debounceTimer;
const blankForm = () => ({ name: '', category_id: '', price: '', discount_price: '', description: '', image: null, gallery: [], existing_gallery: [], remove_gallery: [], delivery_mode: 'inherit', is_available: true, is_featured: false, sort_order: 0, branch_assignments: (props.branches || []).map(branch => ({ branch_id: branch.id, enabled: true, price: '', discount_price: '', is_available: true, stock: '' })) });
const form = ref(blankForm());
const galleryError = ref('');
const enabledCount = computed(() => form.value.branch_assignments.filter(a => a.enabled).length);
const assetUrl = (path) => path?.startsWith('http') ? path : '/storage/' + path;
const money = (value) => Number(value || 0).toLocaleString('en-BD', { maximumFractionDigits: 0 });
const branchName = (id) => props.branches.find(branch => Number(branch.id) === Number(id))?.name || 'Outlet';
const debouncedSearch = () => { clearTimeout(debounceTimer); debounceTimer = setTimeout(doFilter, 350); };
const doFilter = () => router.get(route('admin.products.index'), { search: search.value, category_id: categoryFilter.value }, { preserveState: true, preserveScroll: true });
const openModal = (product = null) => { editing.value = product; galleryError.value = ''; if (!product) { form.value = blankForm(); showModal.value = true; return; } const productBranches = Object.fromEntries((product.branches || []).map(branch => [branch.id, branch])); form.value = { name: product.name, category_id: product.category_id, price: product.price, discount_price: product.discount_price || '', description: product.description || '', image: null, gallery: [], existing_gallery: product.gallery || [], remove_gallery: [], delivery_mode: product.delivery_mode || 'inherit', is_available: !!product.is_available, is_featured: !!product.is_featured, sort_order: product.sort_order || 0, branch_assignments: (props.branches || []).map(branch => { const row = productBranches[branch.id]; const pivot = row?.pivot || {}; return { branch_id: branch.id, enabled: !!row, price: pivot.price ?? '', discount_price: pivot.discount_price ?? '', is_available: pivot.is_available === undefined ? true : !!pivot.is_available, stock: pivot.stock ?? '' }; }) }; showModal.value = true; };
const handleGalleryFiles = (event) => { const files = Array.from(event.target.files || []); const invalid = files.find(file => !file.type.startsWith('image/') || file.size > 4 * 1024 * 1024); galleryError.value = invalid ? 'Each gallery image must be an image smaller than 4MB.' : ''; if (!invalid) form.value.gallery = [...form.value.gallery, ...files]; event.target.value = ''; };
const removeExistingImage = (path) => { form.value.existing_gallery = form.value.existing_gallery.filter(item => item !== path); form.value.remove_gallery.push(path); };
const saveProduct = () => { if (galleryError.value) return; saving.value = true; const data = new FormData(); ['name', 'category_id', 'price', 'discount_price', 'description', 'sort_order', 'delivery_mode'].forEach(key => { if (form.value[key] !== null && form.value[key] !== '') data.append(key, form.value[key]); }); data.append('is_available', form.value.is_available ? '1' : '0'); data.append('is_featured', form.value.is_featured ? '1' : '0'); data.append('branch_assignments', JSON.stringify(form.value.branch_assignments.filter(a => a.enabled))); data.append('remove_gallery', JSON.stringify(form.value.remove_gallery)); if (form.value.image) data.append('image', form.value.image); form.value.gallery.forEach(file => data.append('gallery[]', file)); const options = { forceFormData: true, onFinish: () => saving.value = false, onSuccess: () => showModal.value = false }; if (editing.value) { data.append('_method', 'PUT'); router.post(route('admin.products.update', editing.value.id), data, options); } else router.post(route('admin.products.store'), data, options); };
const deleteProduct = (product) => { if (confirm(`Delete ${product.name}?`)) router.delete(route('admin.products.destroy', product.id)); };
</script>
