<template>
    <CustomerLayout>
        <section v-if="activeCoupons.length" class="coupon-ticker relative z-20 w-full overflow-hidden border-b border-gold-300/30 bg-brand-950 text-cream-50">
            <div class="mx-auto flex min-h-11 w-full max-w-7xl items-center gap-3 px-4 sm:px-6 lg:px-8">
                <span class="relative z-10 inline-flex shrink-0 items-center gap-2 rounded-full bg-gold-500 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-brand-950 shadow-soft"><span class="h-1.5 w-1.5 rounded-full bg-brand-950"></span>Live offers</span>
                <div class="coupon-ticker-viewport min-w-0 flex-1"><div class="coupon-ticker-track">
                    <span v-for="(coupon, index) in tickerCoupons" :key="`${coupon.id}-${index}`" class="inline-flex shrink-0 items-center gap-2 px-5 text-xs font-semibold sm:text-sm"><strong class="text-gold-300">{{ couponOffer(coupon) }}</strong><span class="text-brand-200">Use code</span><b class="rounded-md border border-white/20 bg-white/10 px-2 py-1 tracking-wider text-cream-50">{{ coupon.code }}</b><span class="text-brand-300">·</span></span>
                </div></div>
            </div>
        </section>

        <section class="reference-home-hero relative overflow-hidden border-b border-brand-100">
            <div class="reference-hero mx-auto max-w-7xl px-0 sm:px-6 lg:px-8">
                <div class="reference-hero-media relative overflow-hidden sm:rounded-[2rem]">
                    <img v-if="heroImage(0)" :src="heroImage(0)" alt="Fresh Lake View bakery" class="reference-hero-image" />
                    <div class="reference-hero-wash"></div>
                    <div class="relative z-10 flex min-h-[570px] flex-col justify-between px-5 pb-7 pt-8 sm:min-h-[610px] sm:px-10 sm:pb-10 sm:pt-12 lg:px-14 lg:pb-12 lg:pt-14">
                        <div class="reference-hero-copy max-w-xl">
                            <div class="inline-flex items-center gap-2 rounded-full border border-gold-200 bg-white/80 px-3 py-2 text-[10px] font-bold uppercase tracking-[.18em] text-gold-700 shadow-soft"><span class="h-2 w-2 animate-pulse rounded-full bg-sage-400"></span>Lake View bakery</div>
                            <p class="mt-5 text-xs font-bold uppercase tracking-[.16em] text-brand-500">{{ branchDisplayName(selectedBranch) || 'Fresh from Satkhira' }}</p>
                            <h1 class="mt-4 max-w-[560px] font-serif text-[clamp(3.2rem,7vw,6.5rem)] font-bold leading-[.88] tracking-[-.06em] text-brand-900">Made for your<br><span class="reference-hero-accent">sweetest days.</span></h1>
                            <p class="mt-6 max-w-lg text-sm leading-7 text-brand-600 sm:text-base">{{ settings.hero_subtitle || 'From everyday breads to celebration cakes, discover something delicious for every kind of day.' }}</p>
                            <div class="mt-7 flex flex-wrap items-center gap-3"><Link :href="route('products.index')" class="btn-primary">Explore the bakery <span>→</span></Link><Link :href="route('custom-cake.index')" class="btn-outline">Make a custom cake</Link></div>
                            <div class="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-brand-500"><span class="inline-flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-sage-400"></span>Freshly baked daily</span><span class="inline-flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-gold-500"></span>Pickup & delivery</span></div>
                            <div v-if="activeCoupons.length" class="reference-offer-card mt-6 max-w-md rounded-2xl border border-gold-200 bg-white/90 p-4 shadow-card backdrop-blur-sm"><div class="flex items-center justify-between gap-3"><div><p class="text-[10px] font-bold uppercase tracking-[.18em] text-gold-700">Sweet offer</p><p class="mt-1 font-serif text-lg font-bold text-brand-900">{{ couponOffer(activeCoupons[0]) }} on your order</p></div><span class="rounded-full bg-brand-100 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-brand-700">Use {{ activeCoupons[0].code }}</span></div><p class="mt-3 text-xs text-brand-500">Fresh treats, a little easier on your pocket today.</p></div>
                        </div>
                        <div v-if="featuredProducts.length" class="reference-featured-desktop absolute bottom-8 right-8 z-10 hidden w-[300px] rotate-2 overflow-hidden rounded-2xl border border-white/80 bg-white/95 shadow-2xl backdrop-blur-sm sm:block lg:bottom-12 lg:right-12"><Link :href="route('products.show', featuredProducts[0].slug)" class="block p-3"><div class="flex items-center gap-3"><div class="h-20 w-20 shrink-0 overflow-hidden rounded-xl bg-brand-50"><img v-if="featuredProducts[0].image" :src="assetUrl(featuredProducts[0].image)" :alt="featuredProducts[0].name" class="h-full w-full object-contain p-1.5"/><span v-else class="flex h-full items-center justify-center text-3xl">{{ productEmoji(featuredProducts[0]) }}</span></div><div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-[.15em] text-gold-700">Featured today</p><h2 class="mt-1 truncate font-serif text-lg font-bold text-brand-900">{{ featuredProducts[0].name }}</h2><p class="mt-1 text-sm font-bold text-brand-600">৳{{ money(featuredProducts[0].effective_price) }} <span class="ml-1 text-xs font-medium text-brand-400">· Tap to view</span></p></div></div></Link></div>
                        <div class="reference-hero-note hidden text-right text-xs font-bold uppercase leading-5 tracking-[.18em] text-brand-500 sm:block">Freshly baked<br><span class="reference-note-accent">in Satkhira</span></div>
                    </div>
                </div>
                <div v-if="featuredProducts.length" class="mt-4 sm:hidden"><Link :href="route('products.show', featuredProducts[0].slug)" class="flex items-center gap-3 rounded-2xl border border-brand-100 bg-white p-3 shadow-soft"><div class="h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-brand-50"><img v-if="featuredProducts[0].image" :src="assetUrl(featuredProducts[0].image)" :alt="featuredProducts[0].name" class="h-full w-full object-contain p-1.5"/><span v-else class="flex h-full items-center justify-center text-2xl">{{ productEmoji(featuredProducts[0]) }}</span></div><div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-[.15em] text-gold-700">Featured today · Tap to view</p><h2 class="mt-1 truncate font-serif text-lg font-bold text-brand-900">{{ featuredProducts[0].name }}</h2><p class="mt-1 text-sm font-bold text-brand-600">৳{{ money(featuredProducts[0].effective_price) }}</p></div><span class="ml-auto text-xl text-brand-400">→</span></Link></div>
            </div>
        </section>

        <div class="overflow-hidden border-y border-brand-600 bg-brand-700 text-cream-50"><div class="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-8 gap-y-1 px-4 py-3 text-xs font-semibold tracking-wide sm:px-6 sm:text-sm lg:px-8"><span>Freshly baked daily ✦</span><span>Handcrafted with care ✦</span><span>Pickup & delivery ✦</span><span>Happiness in every bite</span></div></div>

        <section v-if="categories.length" class="section-shell"><div class="mx-auto max-w-xl text-center"><p class="eyebrow justify-center">Explore the bakery</p><h2 class="section-title">Something for every craving</h2><p class="section-copy">Browse our handcrafted selection, prepared for {{ branchDisplayName(selectedBranch) || 'your local outlet' }}.</p></div><div class="relative mt-10 sm:hidden"><div ref="categoryTrack" class="category-rail scrollbar-hide flex snap-x snap-mandatory gap-3 overflow-x-auto pb-3"><Link v-for="cat in categories" :key="cat.id" :href="route('products.index', { category: cat.slug })" class="category-slide group w-[132px] shrink-0 snap-start rounded-2xl border border-brand-100 bg-white p-2.5 text-center shadow-soft"><div class="aspect-square overflow-hidden rounded-xl bg-brand-50"><img v-if="cat.image" :src="assetUrl(cat.image)" :alt="cat.name" loading="lazy" class="h-full w-full object-contain p-1.5 transition group-hover:scale-105"/><span v-else class="flex h-full items-center justify-center text-3xl font-serif font-bold text-brand-400">{{ categoryMark(cat.name) }}</span></div><span class="mt-2 block truncate text-xs font-bold text-brand-700">{{ cat.name }}</span></Link></div><div class="mt-3 flex items-center justify-between gap-3"><span class="text-[11px] text-brand-400">Swipe to browse categories</span><button type="button" @click="categoryMenuOpen = true" class="rounded-full border border-brand-300 bg-white px-4 py-2 text-xs font-bold text-brand-700 shadow-soft">All categories</button></div></div><div class="mt-10 hidden grid-cols-2 gap-3 sm:grid sm:grid-cols-4 sm:gap-4 lg:grid-cols-8"><Link v-for="cat in categories" :key="cat.id" :href="route('products.index', { category: cat.slug })" class="group rounded-2xl border border-brand-100 bg-white p-3 text-center shadow-soft transition hover:-translate-y-1 hover:shadow-card"><div class="aspect-square overflow-hidden rounded-xl bg-brand-50"><img v-if="cat.image" :src="assetUrl(cat.image)" :alt="cat.name" loading="lazy" class="h-full w-full object-contain p-1.5 transition group-hover:scale-105"/><span v-else class="flex h-full items-center justify-center text-3xl font-serif font-bold text-brand-400">{{ categoryMark(cat.name) }}</span></div><span class="mt-3 block text-xs font-semibold text-brand-700 group-hover:text-brand-500 sm:text-sm">{{ cat.name }}</span></Link></div></section>

        <section v-if="bestSellingProducts.length" class="border-y border-brand-100 bg-cream-100"><div class="section-shell"><div class="flex items-end justify-between gap-5"><div><p class="eyebrow">Most loved</p><h2 class="section-title text-left">Our bestsellers</h2><p class="section-copy text-left">The bakes customers keep coming back for.</p></div><Link :href="route('products.index')" class="hidden text-sm font-bold text-brand-600 hover:text-brand-500 sm:inline-flex">View all <span class="ml-2">→</span></Link></div><div class="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 sm:gap-6 lg:grid-cols-4"><ProductCard v-for="product in bestSellingProducts" :key="product.id" :product="product" @add="addToCart" /></div><div class="mt-8 text-center sm:hidden"><Link :href="route('products.index')" class="btn-outline">View all products</Link></div></div></section>

        <section v-if="allProducts.length" class="section-shell"><div class="flex items-end justify-between gap-5"><div><p class="eyebrow">Fresh counter</p><h2 class="section-title text-left">All products</h2><p class="section-copy text-left">Explore the full selection available at your outlet.</p></div><Link :href="route('products.index')" class="text-sm font-bold text-brand-600 hover:text-brand-500">Shop all <span class="ml-2">→</span></Link></div><div class="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 sm:gap-6 lg:grid-cols-4"><ProductCard v-for="product in displayedAllProducts" :key="product.id" :product="product" @add="addToCart" /></div><div v-if="allProducts.length > 8" class="mt-8 flex justify-center"><button type="button" @click="showAllProducts = !showAllProducts" class="inline-flex items-center gap-2 rounded-full border border-brand-300 bg-white px-5 py-3 text-sm font-bold text-brand-700 shadow-soft transition hover:-translate-y-0.5 hover:border-brand-500 hover:bg-brand-50">{{ showAllProducts ? "Show fewer products" : "Show all products" }} <span>{{ showAllProducts ? "↑" : "↓" }}</span></button></div></section>

        <section class="section-shell"><div class="grid items-center gap-10 lg:grid-cols-2"><div class="relative min-h-[330px] sm:min-h-[430px]"><div class="absolute inset-0 w-[72%] overflow-hidden rounded-[3rem_0_3rem_0] bg-brand-200"><img v-if="heroImage(3)" :src="heroImage(3)" loading="lazy" class="h-full w-full object-cover" alt="Lake View bakery"/><div v-else class="flex h-full w-full items-center justify-center bg-gradient-to-br from-brand-700 to-brand-950 text-5xl font-serif font-bold text-gold-200">LV</div></div><div class="absolute bottom-0 right-0 h-[47%] w-[45%] overflow-hidden rounded-[0_2rem_0_2rem] border-8 border-cream-50 bg-gold-100 shadow-card"><img v-if="heroImage(4)" :src="heroImage(4)" loading="lazy" class="h-full w-full object-cover" alt="Lake View sweets"/><div v-else class="flex h-full w-full items-center justify-center bg-gradient-to-br from-gold-300 to-brand-500 text-4xl font-serif font-bold text-brand-950">LV</div></div></div><div><p class="eyebrow">Made with intention</p><h2 class="section-title text-left">A little sweetness for every kind of day.</h2><p class="section-copy mt-5 text-left">{{ settings.about_text || 'We believe the best memories often start with something warm from the oven. Our bakers prepare every bite with honest ingredients, time and a whole lot of love.' }}</p><div class="mt-7 grid grid-cols-2 gap-3"><div class="rounded-2xl border border-brand-100 bg-brand-50 p-4"><div class="font-serif text-2xl font-bold text-brand-600">7+</div><div class="mt-1 text-xs text-brand-500">local outlets</div></div><div class="rounded-2xl border border-gold-100 bg-gold-50 p-4"><div class="font-serif text-2xl font-bold text-brand-600">100+</div><div class="mt-1 text-xs text-brand-500">fresh products</div></div></div><Link :href="route('about')" class="mt-7 inline-flex items-center gap-2 text-sm font-bold text-brand-600 hover:text-brand-500">Our story <span>→</span></Link></div></div></section>

        <section class="bg-brand-950 text-cream-50"><div class="section-shell py-16 sm:py-20"><div class="flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-end"><div><p class="eyebrow text-gold-300">Find us near you</p><h2 class="mt-3 font-serif text-3xl font-bold sm:text-4xl">Our outlets</h2><p class="mt-3 max-w-xl text-brand-200">Choose an outlet above and we’ll keep your shopping experience local.</p></div><Link :href="route('contact')" class="btn-light">See all locations</Link></div><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div v-for="branch in branches" :key="branch.id" class="rounded-2xl border border-brand-700 bg-brand-900/60 p-5"><div class="flex items-start gap-3"><span class="outlet-icon">⌖</span><div><h3 class="font-semibold text-cream-50">{{ branch.name }}</h3><p v-if="branch.name_bn" class="mt-0.5 text-xs font-medium text-brand-300">{{ branch.name_bn }}</p><p class="mt-2 text-xs leading-5 text-brand-200">{{ branch.address || 'Lake View Sweets & Bakery outlet' }}</p><a v-if="branch.phones?.[0]" :href="'tel:' + branch.phones[0]" class="mt-3 inline-block text-xs text-gold-300">{{ branch.phones[0] }}</a></div></div></div></div></div></section>

        <Teleport to="body"><Transition name="fade"><div v-if="categoryMenuOpen" class="fixed inset-0 z-[110] flex items-end justify-center bg-brand-950/55 p-3 backdrop-blur-sm sm:items-center sm:p-5" @click.self="categoryMenuOpen = false"><div class="w-full max-w-2xl rounded-[2rem] bg-cream-50 p-5 shadow-2xl sm:p-8"><div class="mb-5 flex items-start justify-between gap-4"><div><p class="eyebrow">Browse the menu</p><h2 class="mt-2 font-serif text-2xl font-bold text-brand-900">All categories</h2><p class="mt-1 text-sm text-brand-500">Choose a category and find your favourite fresh bakes.</p></div><button type="button" @click="categoryMenuOpen = false" class="icon-button bg-brand-100" aria-label="Close">×</button></div><div class="grid max-h-[58vh] grid-cols-2 gap-3 overflow-y-auto pr-1 sm:grid-cols-3"><Link v-for="cat in categories" :key="`modal-${cat.id}`" :href="route('products.index', { category: cat.slug })" @click="categoryMenuOpen = false" class="flex items-center gap-3 rounded-2xl border border-brand-100 bg-white p-3 text-left transition hover:border-brand-400 hover:shadow-soft"><span class="h-12 w-12 shrink-0 overflow-hidden rounded-xl bg-brand-50"><img v-if="cat.image" :src="assetUrl(cat.image)" :alt="cat.name" class="h-full w-full object-contain p-1"/><span v-else class="flex h-full items-center justify-center font-serif font-bold text-brand-500">{{ categoryMark(cat.name) }}</span></span><span class="min-w-0 truncate text-sm font-bold text-brand-800">{{ cat.name }}</span></Link></div></div></div></Transition></Teleport>

        <Transition name="toast"><div v-if="toast.show" class="fixed bottom-6 right-4 z-[80] flex max-w-sm items-center gap-3 rounded-2xl border border-gold-300 bg-white p-4 shadow-card"><span class="flex h-10 w-10 items-center justify-center rounded-full bg-sage-50 text-sage-600">✓</span><div class="min-w-0"><div class="text-sm font-bold text-brand-900">Added to your bag</div><div class="truncate text-xs text-brand-500">{{ toast.product?.name }}</div></div><Link :href="route('checkout.index')" class="btn-mini ml-auto">View bag</Link></div></Transition>
    </CustomerLayout>
</template>

<script setup>
import CustomerLayout from '@/Layouts/CustomerLayout.vue';
import ProductCard from '@/Components/ProductCard.vue';
import { Link, usePage } from '@inertiajs/vue3';
import { computed, onMounted, onUnmounted, ref } from 'vue';

defineProps({ categories: Array, featuredProducts: Array, bestSellingProducts: Array, allProducts: Array, branches: Array, selectedBranch: Object, activeCoupons: Array });
const page = usePage();
const settings = computed(() => page.props.settings || {});
const selectedBranch = computed(() => page.props.selectedBranch || null);
const featuredProducts = computed(() => page.props.featuredProducts || []);
const bestSellingProducts = computed(() => page.props.bestSellingProducts || featuredProducts.value);
const allProducts = computed(() => page.props.allProducts || []);
const showAllProducts = ref(false);
const displayedAllProducts = computed(() => showAllProducts.value ? allProducts.value : allProducts.value.slice(0, 8));
const categories = computed(() => page.props.categories || []);
const branches = computed(() => page.props.branches || []);
const activeCoupons = computed(() => page.props.activeCoupons || []);
const tickerCoupons = computed(() => [...activeCoupons.value, ...activeCoupons.value]);
const categoryMenuOpen = ref(false);
const categoryTrack = ref(null);
const featuredTrack = ref(null);
let featuredTimer = null;
const stopFeaturedTicker = () => { if (featuredTimer) { window.clearInterval(featuredTimer); featuredTimer = null; } };
const startFeaturedTicker = () => { stopFeaturedTicker(); featuredTimer = window.setInterval(() => { const rail = featuredTrack.value; const card = rail?.querySelector('.featured-hero-card'); if (!rail || !card || rail.scrollWidth <= rail.clientWidth + 8) return; const step = card.getBoundingClientRect().width + 12; const max = rail.scrollWidth - rail.clientWidth; rail.scrollTo({ left: rail.scrollLeft + step >= max - 4 ? 0 : rail.scrollLeft + step, behavior: 'smooth' }); }, 4200); };
onMounted(startFeaturedTicker);
onUnmounted(stopFeaturedTicker);
const toast = ref({ show: false, product: null });
let toastTimer;

const assetUrl = path => path?.startsWith('http') ? path : '/storage/' + path;
const branchDisplayName = branch => branch?.name_bn ? `${branch.name} · ${branch.name_bn}` : branch?.name || '';
const money = value => Number(value || 0).toLocaleString('en-BD', { maximumFractionDigits: 0 });
const couponOffer = coupon => coupon.type === 'percentage' ? `${coupon.value}% off` : `৳${money(coupon.value)} off`;
const categoryMark = name => ({ Cake: 'CK', Bread: 'BR', Cookies: 'CO', Sweets: 'SW', 'Fast Food': 'FF', Toast: 'TO', Dessert: 'DS', 'Order Cake': 'OC' }[name] || 'LV');
const productEmoji = product => ({ Cake: '🎂', Bread: '🍞', Cookies: '🍪', Sweets: '🍬', 'Fast Food': '🍔', Dessert: '🍮' }[product?.category?.name] || '🍰');
const fallbackHeroImages = ['/images/lakeview-hero.jpg', '/images/lakeview-sweets.jpg', '/images/lakeview-cake.jpg'];
const heroImages = computed(() => { try { const configured = JSON.parse(settings.value.hero_images || '[]').filter(Boolean); return configured.length ? configured : fallbackHeroImages; } catch { return fallbackHeroImages; } });
const heroImage = index => heroImages.value[index % heroImages.value.length] || '';
const addToCart = (product, amount = 1) => { let cart = []; try { cart = JSON.parse(localStorage.getItem('cart') || '[]'); } catch { cart = []; } const existing = cart.find(item => item.product_id === product.id); if (existing) { existing.quantity += amount; existing.image = product.image || existing.image; existing.category_name = product.category?.name || existing.category_name || ''; existing.allow_pickup = product.allow_pickup !== false; existing.allow_home_delivery = product.allow_home_delivery !== false; existing.allow_national_delivery = product.allow_national_delivery === true; } else cart.push({ product_id: product.id, name: product.name, category_name: product.category?.name || '', image: product.image || '', price: Number(product.effective_price), quantity: amount, allow_pickup: product.allow_pickup !== false, allow_home_delivery: product.allow_home_delivery !== false, allow_national_delivery: product.allow_national_delivery === true }); localStorage.setItem('cart', JSON.stringify(cart)); window.dispatchEvent(new Event('cart-updated')); toast.value = { show: true, product }; clearTimeout(toastTimer); toastTimer = window.setTimeout(() => { toast.value.show = false; }, 3200); };
</script>
