<template>
    <AdminLayout active-menu="branches" page-title="Branches">
        <div class="space-y-5">
            <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
                <div><p class="text-xs font-bold uppercase tracking-[.2em] text-brand-400">Outlet network</p><h2 class="mt-2 font-serif text-3xl font-bold text-brand-900">Your branches</h2><p class="mt-2 text-sm text-brand-500">Manage outlets that customers can choose before shopping.</p></div>
                <button @click="openModal()" class="rounded-full bg-brand-700 px-5 py-3 text-sm font-bold text-white transition hover:bg-brand-600">+ Add branch</button>
            </div>
            <div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="stat-card"><span class="stat-label">Total outlets</span><span class="stat-value">{{ branches.length }}</span></div><div class="stat-card"><span class="stat-label">Live outlets</span><span class="stat-value">{{ branches.filter(b => b.is_active).length }}</span></div><div class="stat-card"><span class="stat-label">Products assigned</span><span class="stat-value">{{ branches.reduce((sum, b) => sum + (b.products_count || 0), 0) }}</span></div><div class="stat-card"><span class="stat-label">Orders received</span><span class="stat-value">{{ branches.reduce((sum, b) => sum + (b.orders_count || 0), 0) }}</span></div></div>
            <div class="overflow-hidden rounded-2xl border border-brand-100 bg-white shadow-soft"><div class="overflow-x-auto"><table class="w-full min-w-[760px]"><thead class="border-b border-brand-100 bg-brand-50"><tr><th class="table-head">Branch</th><th class="table-head">Contact</th><th class="table-head">Products</th><th class="table-head">Orders</th><th class="table-head">Status</th><th class="table-head">Actions</th></tr></thead><tbody class="divide-y divide-brand-100"><tr v-for="branch in branches" :key="branch.id" class="transition hover:bg-cream-50"><td class="table-cell"><div class="flex items-center gap-3"><div class="flex h-11 w-11 items-center justify-center overflow-hidden rounded-xl bg-brand-100 text-xl"><img v-if="branch.image" :src="assetUrl(branch.image)" class="h-full w-full object-cover"/><span v-else>⌖</span></div><div><div class="font-semibold text-brand-900">{{ branch.name }}</div><div v-if="branch.name_bn" class="mt-0.5 text-xs text-brand-500">{{ branch.name_bn }}</div><div class="mt-1 text-xs text-brand-400">{{ branch.address || 'Address not added' }}</div></div></div></td><td class="table-cell text-brand-500">{{ branch.phones?.join(', ') || '—' }}</td><td class="table-cell font-semibold text-brand-700">{{ branch.products_count || 0 }}</td><td class="table-cell text-brand-500">{{ branch.orders_count || 0 }}</td><td class="table-cell"><span :class="branch.is_active ? 'status-success' : 'status-danger'">{{ branch.is_active ? 'Live' : 'Hidden' }}</span></td><td class="table-cell"><button @click="openModal(branch)" class="mr-4 text-sm font-semibold text-brand-600 hover:text-brand-500">Edit</button><button @click="deleteBranch(branch)" class="text-sm font-semibold text-red-500 hover:text-red-700">Delete</button></td></tr></tbody></table></div></div>
        </div>

        <div v-if="showModal" class="fixed inset-0 z-[100] flex items-center justify-center bg-brand-950/60 p-4 backdrop-blur-sm" @click.self="showModal = false"><div class="w-full max-w-lg rounded-3xl bg-cream-50 p-6 shadow-2xl sm:p-8"><div class="mb-6 flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-brand-400">Outlet details</p><h3 class="mt-2 font-serif text-2xl font-bold text-brand-900">{{ editing ? 'Edit branch' : 'Add branch' }}</h3></div><button @click="showModal = false" class="h-9 w-9 rounded-full bg-brand-100 text-brand-600">×</button></div><form @submit.prevent="saveBranch" class="space-y-4"><div class="grid gap-4 sm:grid-cols-2"><label class="field-label">Branch name<input v-model="form.name" required class="field-input" /></label><label class="field-label">বাংলা নাম <span class="font-normal text-brand-400">(optional)</span><input v-model="form.name_bn" placeholder="যেমন: প্রধান শাখা" class="field-input" /></label></div><label class="field-label">Address<textarea v-model="form.address" rows="2" class="field-input"></textarea></label><div><div class="field-label">Phone numbers</div><div v-for="(phone, i) in form.phones" :key="i" class="mt-2 flex gap-2"><input v-model="form.phones[i]" class="field-input mt-0" placeholder="01XXXXXXXXX"/><button type="button" @click="form.phones.splice(i, 1)" class="w-10 rounded-xl bg-red-50 text-red-500">×</button></div><button type="button" @click="form.phones.push('')" class="mt-2 text-xs font-bold text-brand-600">+ Add another number</button></div><label class="field-label">Branch image<input @change="e => form.image = e.target.files[0]" type="file" accept="image/*" class="field-input file:mr-3 file:rounded-full file:border-0 file:bg-brand-100 file:px-3 file:py-1 file:text-xs file:font-bold file:text-brand-700" /></label><div class="grid grid-cols-2 gap-4"><label class="field-label">Sort order<input v-model="form.sort_order" type="number" min="0" class="field-input" /></label><label class="inline-flex items-center gap-2 self-end pb-3 text-sm font-semibold text-brand-700"><input v-model="form.is_active" type="checkbox" class="rounded border-brand-300 text-brand-600"/> Live branch</label></div><div class="flex gap-3 pt-2"><button type="submit" :disabled="saving" class="flex-1 rounded-full bg-brand-700 py-3 text-sm font-bold text-white hover:bg-brand-600 disabled:opacity-60">{{ saving ? 'Saving...' : editing ? 'Save changes' : 'Create branch' }}</button><button type="button" @click="showModal = false" class="rounded-full border border-brand-200 px-6 py-3 text-sm font-bold text-brand-700">Cancel</button></div></form></div></div>
    </AdminLayout>
</template>

<script setup>
import AdminLayout from '@/Layouts/AdminLayout.vue';
import { router } from '@inertiajs/vue3';
import { ref } from 'vue';

const props = defineProps({ branches: Array });
const branches = props.branches || [];
const showModal = ref(false); const editing = ref(null); const saving = ref(false); const form = ref({ name: '', name_bn: '', address: '', phones: [''], image: null, sort_order: 0, is_active: true });
const assetUrl = (path) => path?.startsWith('http') ? path : '/storage/' + path;
const openModal = (branch = null) => { editing.value = branch; form.value = branch ? { name: branch.name, name_bn: branch.name_bn || '', address: branch.address || '', phones: branch.phones?.length ? [...branch.phones] : [''], image: null, sort_order: branch.sort_order || 0, is_active: !!branch.is_active } : { name: '', name_bn: '', address: '', phones: [''], image: null, sort_order: 0, is_active: true }; showModal.value = true; };
const saveBranch = () => { saving.value = true; const data = new FormData(); data.append('name', form.value.name); data.append('name_bn', form.value.name_bn || ''); data.append('address', form.value.address || ''); data.append('sort_order', form.value.sort_order || 0); data.append('is_active', form.value.is_active ? '1' : '0'); form.value.phones.filter(Boolean).forEach((phone, i) => data.append(`phones[${i}]`, phone)); if (form.value.image) data.append('image', form.value.image); const options = { forceFormData: true, onFinish: () => saving.value = false, onSuccess: () => showModal.value = false }; if (editing.value) { data.append('_method', 'PUT'); router.post(route('admin.branches.update', editing.value.id), data, options); } else router.post(route('admin.branches.store'), data, options); };
const deleteBranch = (branch) => { if (confirm(`Delete ${branch.name}?`)) router.delete(route('admin.branches.destroy', branch.id)); };
</script>
